### ISSUE TITLE
SpUtils Crash

### ISSUE THREAD

**Issue by JiyeHoo** [dreamncn/bluetooth#9]
打开应用存在立刻 Crash

**环境：**
- Android 14
- Lsposed

**导致 crash 的代码：**
`val sp: SharedPreferences = context.getSharedPreferences(NAME, Context.MODE_WORLD_READABLE)`

**Logcat error 信息：**
`java.lang.ExceptionInInitializerError
	at net.ankio.bluetooth.utils.SpUtils.getString(SpUtils.kt:20)
	at net.ankio.bluetooth.App$Companion.getLocale(App.kt:24)
	at net.ankio.bluetooth.App.onCreate(App.kt:40)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6998)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
	at android.app.ContextImpl.checkMode(ContextImpl.java:3539)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:597)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:587)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:221)
	at net.ankio.bluetooth.utils.SpUtilsKt.<clinit>(SpUtils.kt:14)`

**分析：**
Android 源码中 MODE_WORLD_READABLE 已经废弃了，api doc 的解释是：
File creation mode: allow all other applications to have read access to the created file.
Starting from Build.VERSION_CODES.N, attempting to use this mode throws a SecurityException.

也就是在 N 以上的 Android  版本中，使用 MODE_WORLD_READABLE 会抛出 SecurityException 错误，
建议增加版本判断，或者使用 MODE_PRIVATE 或其他方式。

**Comment by dreamncn** [comment]
这不是BUG
该方案在LSPosed API 93以上版本中可用：https://github.com/LSPosed/LSPosed/wiki/New-XSharedPreferences <https://github.com/LSPosed/LSPosed/wiki/New-XSharedPreferences>

需要先激活模块才能正常使用。
—————————
Ankio 敬上
***@***.***
若无闲事挂心头，便是人间好时节。

**Comment by JiyeHoo** [comment]
感谢，Lsposed 没成功启用插件导致的，重启已经解决。

另外，scan 页面卡顿严重，推测蓝牙扫描占用了主线程，是否可以通过异步处理等方式减少卡顿？

**Comment by AnkioTomas** [comment]
卡顿的问题注意到了，试试新版本：https://github.com/AnkioTomas/bluetooth/releases/
